### ISSUE TITLE
Which is the correct repo?

### ISSUE THREAD

**Issue by irux** [anyswap/multichain-smart-contracts#2]
Hello, I am pretty interested in using multichain bridge for my project, but I don't know which repo is the correct one. Everytime I find a repo with different implementations. Is this repo the correct one or this one ? https://github.com/anyswap/anyswap-v1-core/blob/master/contracts/AnyswapV6ERC20.sol

Thank you !

**Comment by jowenshaw** [comment]
<https://github.com/anyswap/anyswap-v1-core/blob/master/contracts/AnyswapV6ERC20.sol> is the current used version, and <https://github.com/anyswap/multichain-smart-contracts/blob/main/contracts/anytoken/MultichainV7ERC20.sol> is the new version still under developing.

This repository is used for new smart contracts of multichain, mainly for bridge, router, and anycall functions.

This repository also have upgradation smart contracts of [anyswap-v1-core](https://github.com/anyswap/anyswap-v1-core.git) with vesrions start from v7.

**Comment by irux** [comment]
Thank you for the clarification! So, I have some questions about the V6 version, but the other repo doesn't have the issues tab enable. Where could I ask or open an issue about the V6 version?

Thank you again

**Comment by jowenshaw** [comment]
the [anyswap-v1-core](https://github.com/anyswap/anyswap-v1-core.git) has enabled the issues tab now. Welcome for your questions there!

**Comment by irux** [comment]
Thank you!
